language: java
sudo: false

jdk:
  - oraclejdk11

script:
  mvn -Dtest=SUTTest test -e

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
