language: java
sudo: false

jdk:
  - oraclejdk11

script:
  mvn -Dtest=SUTTest test -e

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 96309d6568c1f32cc11d07590814d8826b7a729b
  keep_history: true
  on:
    branch: master
